import "swiper/css";
import "swiper/css/bundle";
import "./index.scss";
import "./js/pages/home";
import "./js/components/form";
import "./js/components/header";
import { WOW } from "wowjs";
import "animate.css";
import "wowjs/css/libs/animate.css";
new WOW().init();
